import React from "react";
import CheckIcon from "./CheckIcon";

// The Subscription component displays the subscription options.
const Subscription = ({ showtext = true }: { showtext?: boolean }) => {

  return (
    <div className="px-5 w-full overflow-y-auto h-[88vh] items-center ">
      <h1 className="text-3xl text-center font-semibold text-redText">
        Unlock your AI Staff Officer now
      </h1>
      <p className="text-sm text-center text-white/70 mt-2">
        100% anonymous. You can cancel anytime.
      </p>
      <div className="flex items-center justify-center mt-10">
      <div className="flex justify-center items-center bg-black min-w-[200px] max-w-[400px]">
        <div className="rounded-xl bg-darkBg py-3 bg-sideBarBg px-12">
          <h1 className="text-3xl text-center text-gray-300 font-semibold">
            Premium Plan
          </h1>

          <h2 className="price-plan text-center">
          <span className="text-sm font-normal">only </span>
          $170.00
          {/* $0.0002 */}
          <span className="text-sm font-normal">
            /month 
            {/* /letter */}
            </span>
            {/* <span className="charge-info text-xs block">Pay for What You Use</span> */}
          </h2>
          <hr className="border-gray-400 w-full" />
          <div className="p-3 mt-2">
            <ul className="space-y-5 text-gray-300 text-sm font-normal">
              <li className="flex gap-2">
                <CheckIcon />
                <div>
                  <h3 className="underline font-bold">Full access</h3>
                  <p>Engage in phone calls</p>
                </div>
              </li>
              {/* <li className="flex gap-2">
                <CheckIcon />
                <div>
                  <h3 className="underline font-bold">Boundless Messaging</h3>
                  <p>Deep Romance</p>
                  <p>Thoughtful Connection</p>
                </div>
              </li> */}
              <li className="flex gap-2">
                <CheckIcon />
                <div>
                  <h3 className="underline font-bold">Transparent pricing</h3>
                  {/* <p>Pay only what you consume</p> */}
                  {/* <p>Pay-as-you-go</p> */}
                  <p>Unlimited access</p>
                  <p>No over-charge</p>
                </div>
              </li>
            </ul>
            <div className="mt-10 flex flex-col gap-3 w-full">
              <form action={process.env.NEXT_PUBLIC_API_URL + "/api/payment-gateway/makePayment"} method="GET">
                <button className="bg-mainBg rounded-lg px-6 py-2 animate-bounce mx-auto block text-lg font-medium">
                Subscribe {showtext ? (<></>):(<> Again</>)}
                </button>
              </form>
            </div>
            <br></br>
            {/* <span className="charge-info text-xs block">*Approx. 5 letters/word. Actual: $0.001/word.</span> */}
            {/* <span className="charge-info text-xs text-center block">*Use it; Pay $0.0002 per letter<br></br>generated by our system.
            <br></br>No Usage, No Charge.
            <br></br>Typical word cost: ~$0.001.</span> */}
                    {/* <span className="charge-info text-xs text-center block">Approx. 5 letters/word: ~$0.001/word.</span> */}
          </div>
        </div>
        
      </div>
      </div>       
    </div>
    
  );
};

export default Subscription;
