import React from 'react'

const page = () => {
  return (
    <div className='w-full h-full flex items-center flex-col px-10 gap-10 justify-center'>
      <div className='text-redText text-3xl font-bold'>Terms and Conditions</div>
      <div className=' text-darkText text-sm text-center whitespace-pre-wrap px-20'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta delectus architecto rerum vitae praesentium aliquam incidunt, necessitatibus debitis voluptate, illum adipisci temporibus ex beatae exercitationem illo sunt earum? Perferendis esse quam, ducimus id vitae voluptatibus natus minus ratione repellat accusamus consequuntur, nulla facilis? Perspiciatis quaerat, perferendis id voluptates consequatur blanditiis eum eligendi provident esse tenetur eveniet quos ad enim, explicabo nesciunt sunt vitae non illo eaque ipsam. Aliquid aut ducimus commodi, minus impedit voluptate totam, magni nam est, provident nemo nobis temporibus! Praesentium quod accusantium ducimus illum voluptatibus. Fugiat, provident sed eos maiores nobis consequuntur vitae itaque dignissimos in voluptatem, facilis, aliquam aut porro numquam quas tempora exercitationem officiis! Necessitatibus modi itaque et, expedita inventore eaque totam obcaecati. Pariatur labore distinctio quos omnis beatae, fuga aut aliquid dolores quo asperiores repudiandae ducimus quod dignissimos delectus. Quaerat reiciendis tempore rem! Quis labore sit culpa doloremque fugiat corporis dolor aut atque autem, alias, dolore laudantium. Cumque voluptatum, animi nobis aut reprehenderit illum voluptas ut rerum recusandae facere quae perferendis dolorum inventore laudantium earum deserunt quia fuga amet accusamus nisi veniam. Sunt eum odit dolore sapiente autem labore quos ipsa, reprehenderit ea temporibus beatae deleniti nobis cumque asperiores suscipit odio dicta pariatur perferendis animi ut. Rerum aut id sed quos neque ut, minima quae laborum ea est animi ducimus hic ipsa, laboriosam facilis consequatur ipsam, consequuntur labore nulla eveniet accusantium! Accusantium non sit ipsum veritatis ex quas aliquam harum reprehenderit quis officiis. Iusto quae cumque, ducimus deserunt quidem qui odit ipsum quia ipsam, rem sit consequatur molestiae consequuntur delectus eaque tempore cupiditate explicabo, aut magnam! Ea cum ut inventore accusamus tempore! Nihil in obcaecati velit consequuntur sit ut rerum perspiciatis autem ullam nobis veniam optio molestias quis saepe quam, dolore placeat iure culpa iusto voluptatibus minus suscipit alias impedit? Vitae quae nihil error.</div>
    </div>
  )
}

export default page
